package model;

public enum Nationality {
	
	USA, MEXICO, CANADA, GUATEMALA, HAITI, CUBA, DOMINICAN_REPUBLIC, HONDURAS, NICARAGUA, SALVADOR, COSTA_RICA, PANAMA, JAMICA, PUERTO_RICO, TRINIDAD_AND_TOBAGO, GUADELOUPE, BELIZE, BAHAMAS, MARTINIQUE, BARBADOS, SAINT_LUCIA, CURACAO, GRENADA, SAINT_VINCENT_AND_THE_GRENADINES, ARUBA,UNITED_STATTES_VIRGIN_ISLANDS, ANTIGUA_AND_BARBUDA,DOMINICA;
	
}
